name: code4mk
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://code4mk.org

# Component versions -- address like site.docker_ce_stable_version
# You can't have - characters in these for non-YAML reasons

# docker_ce_stable_version: "17.09"
# latest_stable_docker_engine_api_version: "1.32"
# docker_ce_edge_version: "17.11"
# docker_ee_version: "17.06"
# compose_version: "1.17.0"
# machine_version: "0.13.0"
# distribution_version: "2.6"

ucp_versions:
  - version: "2.2"
    latest: true
    path: /datacenter/ucp/2.2/guides/
  - version: "2.1"
    path: /datacenter/ucp/2.1/guides/
  - version: "2.0"
    path: /datacenter/ucp/2.0/guides/
  - version: "1.1"
    path: /datacenter/ucp/1.1/overview/

dtr_versions:
  - version: "2.4"
    path: /datacenter/dtr/2.4/guides/
    latest: true
  - version: "2.3"
    path: /datacenter/dtr/2.3/guides/
  - version: "2.2"
    path: /datacenter/dtr/2.2/guides/
  - version: "2.1"
    path: /datacenter/dtr/2.1/guides/
  - version: "2.0"
    path: /datacenter/dtr/2.0/

tablabels:
  ucp-3.0: Universal Control Plane 3.0
  ucp-2.2: Universal Control Plane 2.2
  docker-cli-linux: Docker CLI on Mac/Linux
  docker-cli-win: Docker CLI on Windows
  kubectl: Kubernetes CLI

collections:
  samples:
    output: true

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-relative-links

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: johndmulhausen
      toc_min: 2
      toc_max: 3
      tree: true
  - scope:
      path: "compose"
    values:
      assignee: "gbarr01"
  - scope:
      path: "cs-engine"
    values:
      assignee: "joaofnfernandes"
  - scope:
      path: "datacenter"
    values:
      assignee: "joaofnfernandes"
  - scope:
      path: "datacenter/ucp"
    values:
      assignee: "jimgalasyn"
  - scope:
      path: "docker-cloud"
    values:
      assignee: "londoncalling"
  - scope:
      path: "docker-for-mac"
    values:
      assignee: "gbarr01"
  - scope:
      path: "docker-for-windows"
    values:
      assignee: "gbarr01"
  - scope:
      path: "docker-hub"
    values:
      assignee: "johndmulhausen"
  - scope:
      path: "docker-store"
    values:
      assignee: "johndmulhausen"
  - scope:
      path: "engine"
    values:
      assignee: "mistyhacks"
      win_latest_build: "docker-17.06.2-ee-5"
  - scope:
      path: "kitematic"
    values:
      assignee: "gbarr01"
  - scope:
      path: "machine"
    values:
      assignee: "gbarr01"
  - scope:
      path: "notary"
    values:
      assignee: "johndmulhausen"
  - scope:
      path: "registry"
    values:
      assignee: "joaofnfernandes"
  - scope:
      path: "swarm"
    values:
      assignee: "mistyhacks"
  - scope:
      path: "toolbox"
    values:
      assignee: "gbarr01"
  - scope:
      path: "javascript-developer/react"
    values:
      assignee: "gbarr01"
  - scope:
      path: "datacenter"
    values:
      ucp_latest_image: "docker/ucp:2.2.4"
      dtr_latest_image: "docker/dtr:2.4.1"
      enterprise: true
  - scope:
      path: "datacenter/dtr/2.4"
    values:
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.4.1"
  - scope:
      path: "datacenter/dtr/2.3"
    values:
      hide_from_sitemap: true
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.3.5"
  - scope:
      path: "datacenter/dtr/2.2"
    values:
      hide_from_sitemap: true
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/dtr:2.2.10"
  - scope:
      path: "datacenter/dtr/2.1"
    values:
      hide_from_sitemap: true
      ucp_version: "2.0"
      dtr_version: "2.1"
  - scope:
      path: "datacenter/dtr/2.0"
    values:
      hide_from_sitemap: true
      ucp_version: "1.1"
      dtr_version: "2.0"
  - scope:
      path: "datacenter/ucp/2.2"
    values:
      ucp_org: "docker"
      ucp_repo: "ucp"
      ucp_version: "2.2.4"
  - scope:
      path: "datacenter/ucp/2.1"
    values:
      hide_from_sitemap: true
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/ucp:2.1.5"
  - scope:
      path: "datacenter/ucp/2.0"
    values:
      hide_from_sitemap: true
      ucp_version: "2.0"
      dtr_version: "2.1"
      docker_image: "docker/ucp:2.0.3"
  - scope:
      path: "datacenter/ucp/1.1"
    values:
      hide_from_sitemap: true
      ucp_version: "1.1"
      dtr_version: "2.0"
  - scope:
      path: "apidocs/v1.3.3"
    values:
      hide_from_sitemap: true
  - scope:
      path: "apidocs/v1.4.0"
    values:
      hide_from_sitemap: true
  - scope:
      path: "apidocs/v2.0.0"
    values:
      hide_from_sitemap: true
  - scope:
      path: "apidocs/v2.0.1"
    values:
      hide_from_sitemap: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
